"use strict";
const firebaseConfig={apiKey:"AIzaSyD0tGJs-gvKWAUIem5X5U3ODZcFv-1fIzM",authDomain:"agrinova-92590.firebaseapp.com",databaseURL:"https://agrinova-92590-default-rtdb.firebaseio.com",projectId:"agrinova-92590",storageBucket:"agrinova-92590.firebasestorage.app",messagingSenderId:"112086641196",appId:"1:112086641196:web:cd76299d5d4c3d25173f89"};
let db=null,firebaseReady=false,currentMode="auto",currentThreshold=40,currentMoisture=null,currentMotor=false,currentTimer={enabled:false,startTime:"",offTime:""},history=[];
const $=id=>document.getElementById(id);const clamp=(v,a,b)=>Math.min(b,Math.max(a,Number(v)||a));

document.addEventListener("DOMContentLoaded",()=>{setupNav();setupControls();updateAll();connectFirebase();});
function setupNav(){const t=$("menuToggle"),m=$("navMenu");t.addEventListener("click",()=>{m.classList.toggle("open");t.querySelector("i").className=m.classList.contains("open")?"fa-solid fa-xmark":"fa-solid fa-bars"});m.querySelectorAll("a").forEach(a=>a.addEventListener("click",()=>{m.classList.remove("open");t.querySelector("i").className="fa-solid fa-bars"}));}
function setupControls(){document.querySelectorAll(".mode-btn").forEach(b=>b.addEventListener("click",()=>setMode(b.dataset.mode)));$("thresholdInput").addEventListener("input",()=>setThresholdUI($("thresholdInput").value));$("saveThreshold").addEventListener("click",saveThreshold);$("motorOn").addEventListener("click",()=>manualMotor(true));$("motorOff").addEventListener("click",()=>manualMotor(false));["timerEnabled","startTime","offTime"].forEach(id=>$(id).addEventListener("change",timerPreview));$("saveTimer").addEventListener("click",saveTimer);}
function connectFirebase(){if(typeof firebase==="undefined"){setConnection(false,"Demo mode");return}try{if(!firebase.apps.length)firebase.initializeApp(firebaseConfig);db=firebase.database();firebaseReady=true;setConnection(true,"Firebase connected");listenFirebase()}catch(e){console.error(e);setConnection(false,"Demo mode")}}
function setConnection(ok,text){$("connection").className="connection "+(ok?"connected":"offline");$("connectionText").textContent=text}
function listenFirebase(){db.ref("sensors").on("value",s=>{const d=s.val()||{};if(d.temperature!=null)setTemp(d.temperature);if(d.moisture!=null)setMoisture(d.moisture);if(d.humidity!=null)setHumidity(d.humidity);updateAll()});db.ref("actuators/pump").on("value",s=>setMotor(Boolean(s.val()),"ESP32 / Firebase"));db.ref("controls").on("value",s=>{const d=s.val()||{};if(d.mode==="auto"||d.mode==="manual")currentMode=d.mode;if(d.autoThreshold!=null){currentThreshold=clamp(d.autoThreshold,10,90);$("thresholdInput").value=currentThreshold}if(d.timerSchedule){const x=d.timerSchedule;currentTimer={enabled:x.enabled!==false,startTime:x.startTime||"",offTime:x.endTime||x.offTime||""};$("timerEnabled").checked=currentTimer.enabled;$("startTime").value=currentTimer.startTime;$("offTime").value=currentTimer.offTime}updateAll()});db.ref("weather").on("value",s=>renderWeather(s.val()||{}));}
function setTemp(v){$("temperature").innerHTML=`${fmt(v)}<small>°C</small>`;if($("weatherTemp").textContent==="--°C"){$("weatherTemp").textContent=`${fmt(v)}°C`;$("weatherText").textContent="Live DHT11 temperature"}}
function setHumidity(v){$("humidity").innerHTML=`${fmt(clamp(v,0,100))}<small>%</small>`;$("weatherHumidity").textContent=`${fmt(clamp(v,0,100))}%`}
function setMoisture(v){currentMoisture=clamp(v,0,100);$("soilMoisture").innerHTML=`${fmt(currentMoisture)}<small>%</small>`;$("moistureBar").style.width=currentMoisture+"%";$("moistureState").textContent=currentMoisture<currentThreshold?"Below threshold":"Moisture is sufficient";history.push({v:currentMoisture,t:new Date().toLocaleTimeString([],{hour:"2-digit",minute:"2-digit"})});if(history.length>12)history.shift();updateChart();}
function setMotor(v,source){currentMotor=!!v;$("motorStatus").textContent=currentMotor?"ON":"OFF";$("statusMotor").textContent=currentMotor?"ON":"OFF";$("motorSource").textContent=source;$("motorIndicator").className=currentMotor?"on":"off";updateAlerts();}
function setMode(mode){currentMode=mode;updateAll();if(firebaseReady)db.ref("controls/mode").set(mode)}
function setThresholdUI(v){currentThreshold=clamp(v,10,90);$("thresholdDisplay").textContent=currentThreshold;$("statusThreshold").textContent=currentThreshold+"%"}
function saveThreshold(){setThresholdUI($("thresholdInput").value);if(firebaseReady)db.ref("controls/autoThreshold").set(currentThreshold);addAlert("good",`AUTO threshold saved at ${currentThreshold}%.`);updateAll()}
function manualMotor(state){if(currentMode!=="manual"){addAlert("warning","Switch to MANUAL mode before controlling the motor.");return}if(firebaseReady)db.ref("actuators/pump").set(state);else setMotor(state,"Demo / Manual");}
function timerPreview(){const en=$("timerEnabled").checked,s=$("startTime").value,o=$("offTime").value;$("timerStatus").textContent=en?"ON":"OFF";if(!en){$("timerNote").textContent="Timer disabled";return}if(!s||!o){$("timerNote").textContent="Set both START and OFF times.";return}$("timerNote").textContent=formatSchedule(s,o)+(s>o?" • crosses midnight":"");}
function saveTimer(){const en=$("timerEnabled").checked,s=$("startTime").value,o=$("offTime").value;if(en&&(!s||!o)){addAlert("warning","Set both START and OFF times before enabling the timer.");return}currentTimer={enabled:en,startTime:s,offTime:o};timerPreview();const data={enabled:en,startTime:s,endTime:o,offTime:o,formattedRange:en?formatSchedule(s,o):"Timer disabled"};if(firebaseReady)db.ref("controls/timerSchedule").set(data);addAlert("good",en?`Timer saved: ${formatSchedule(s,o)}`:"Irrigation timer disabled.")}
function renderWeather(d){if(d.temperature!=null)$("weatherTemp").textContent=`${d.temperature}°C`;if(d.description)$("weatherText").textContent=d.description;if(d.location)$("weatherLocation").textContent=d.location;if(d.humidity!=null)$("weatherHumidity").textContent=`${d.humidity}%`}
function updateAll(){document.querySelectorAll(".mode-btn").forEach(b=>b.classList.toggle("active",b.dataset.mode===currentMode));$("autoSection").classList.toggle("hidden",currentMode!=="auto");$("manualSection").classList.toggle("hidden",currentMode!=="manual");$("modeStatus").textContent=currentMode.toUpperCase();setThresholdUI(currentThreshold);timerPreview();if(currentMoisture==null){$("logicBanner").innerHTML='<i class="fa-solid fa-circle-info"></i><span>Waiting for live soil moisture data.</span>'}else if(currentMode==="auto"){$("logicBanner").innerHTML=currentMoisture<currentThreshold?`<i class="fa-solid fa-droplet"></i><span>Soil moisture is ${currentMoisture}%. AUTO requests the motor ON.</span>`:`<i class="fa-solid fa-circle-check"></i><span>Soil moisture is ${currentMoisture}%. AUTO keeps the motor OFF.</span>`}else $("logicBanner").innerHTML='<i class="fa-solid fa-hand"></i><span>MANUAL mode is active. Motor is controlled by the user.</span>';updateAlerts()}
function updateAlerts(){const a=[];if(currentMoisture!=null)a.push(currentMoisture<currentThreshold?{t:"warning",m:`Soil moisture is low (${currentMoisture}%).`}:{t:"good",m:`Soil moisture is above the ${currentThreshold}% threshold.`});if(currentMode==="auto"&&currentMoisture!=null&&currentMoisture<currentThreshold&&!currentMotor)a.push({t:"danger",m:"AUTO mode expects irrigation, but the motor is OFF."});if(currentTimer.enabled&&currentTimer.startTime&&currentTimer.offTime)a.push({t:"good",m:`Timer active: ${formatSchedule(currentTimer.startTime,currentTimer.offTime)}.`});if(!a.length)a.push({t:"neutral",m:"No active farm alerts."});$("alertsList").innerHTML=a.map(x=>`<div class="alert ${x.t}"><i class="fa-solid ${x.t==="danger"?"fa-triangle-exclamation":x.t==="warning"?"fa-circle-exclamation":x.t==="good"?"fa-circle-check":"fa-circle-info"}"></i><span>${esc(x.m)}</span></div>`).join("")}
function addAlert(type,msg){const d=document.createElement("div");d.className=`alert ${type}`;d.innerHTML=`<i class="fa-solid fa-circle-info"></i><span>${esc(msg)}</span>`;$("alertsList").prepend(d);while($("alertsList").children.length>4)$("alertsList").lastElementChild.remove()}
let chart;function setupChart(){const c=$("moistureChart");if(!c||typeof Chart==="undefined")return;chart=new Chart(c.getContext("2d"),{type:"line",data:{labels:[],datasets:[{data:[],borderColor:"#5cad3b",backgroundColor:"rgba(92,173,59,.12)",borderWidth:3,fill:true,tension:.35,pointRadius:3,pointBackgroundColor:"#164d2d"}]},options:{responsive:true,maintainAspectRatio:false,plugins:{legend:{display:false}},scales:{y:{min:0,max:100,ticks:{callback:v=>v+"%"},grid:{color:"rgba(22,77,45,.07)"}},x:{grid:{display:false}}}}})}
function updateChart(){if(!chart)return;chart.data.labels=history.map(x=>x.t);chart.data.datasets[0].data=history.map(x=>x.v);chart.update("none")}
function formatSchedule(s,o){return `${format12(s)} – ${format12(o)}`}function format12(t){if(!t)return"";let[a,b]=t.split(":").map(Number);return`${a%12||12}:${String(b).padStart(2,"0")} ${a>=12?"PM":"AM"}`}function fmt(v){v=Number(v);return Number.isFinite(v)?(Number.isInteger(v)?v:v.toFixed(1)):"--"}function esc(v){return String(v).replaceAll("&","&amp;").replaceAll("<","&lt;").replaceAll(">","&gt;").replaceAll('"',"&quot;").replaceAll("'","&#039;")}
